### ISSUE TITLE
Handle `Handlebars.Safestring` correctly

### ISSUE THREAD

**Issue by nknapp** [nknapp/promised-handlebars#25]
As reported in #22, promises resolving to a `Handlebars.Safestring`-objects will not be handled correctly. 
A test-case is included in #22.

**Comment by nknapp** [comment]
This only seems to apply to block helper usage. (`{{#test}}{{/test}}`)

**Comment by ehlerskon** [comment]
I had the same issue. 

commit [109bdbf](https://github.com/nknapp/promised-handlebars/pull/22/commits/109bdbf53b9579952c20b5788a195bfc896dfaef) fixed the bug.

Would be great if you merge the pull request and create a release?

Thanks

**Comment by nknapp** [comment]
Commit 109bdbf does not fix the test case provided in #22. I'm trying this now on a branch [test-pr22](https://github.com/nknapp/promised-handlebars/tree/test-pr22). I've added the test and the fix and the [Travis Build](https://travis-ci.org/nknapp/promised-handlebars/jobs/155257087#L246) fails on the test.

If you can provide another failing test that is merged by this, I'd be happy to merge, but until I know *what* the problem is that is fixed by the commit, I would rather not make this change.

**Comment by nknapp** [comment]
OK, the fix avoids the exception but it does not fix the test case. Instead of the correct string, the Promise.toString()-representation is inserted.

**Comment by nknapp** [comment]
I have added a fix in #27. I would like to await some review or comments before fixing. 

Although this is duplicated thougout #22 and several commit messages now: 

The fix provided in #22 did not fix the problem. It just avoids the exception being thrown. The real fix is a special handling of SafeString which is essentially done in #27. It is more complicated which is why I would like to have some review before merging it. Maybe there is a simpler solution but I doubt it.

**Comment by nknapp** [comment]
Fixed in 2.0.1
