### ISSUE TITLE
call compile in registerHelper

### ISSUE THREAD

**Issue by yyxiong** [nknapp/promised-handlebars#30]
the render result is string, not dom element, and {{expr}} not work

helper register
`
Handlebars.registerHelper("inject", function(path, options) {
  ...
  return  Handlebars.compile(fileContent);
})
`

call helper
`
{{inject "common/test"}}
`

render result
`
<div class="main-left">
  &lt;div class&#x3D;&quot;sidebar js-comp&quot; data-comp-path&#x3D;&quot;common/sidebar&quot;&gt;&lt;div class&#x3D;&quot;sidebar&quot;&gt;
  &lt;ul class&#x3D;&quot;sidebar-portal&quot;&gt;
    &lt;li class&#x3D;&quot;portal-item current-portal&quot;&gt;
      &lt;span class&#x3D;&quot;portal-icon&quot;&gt;&lt;em class&#x3D;&quot;icon-zcy icon-location&quot;&gt;&lt;/em&gt;&lt;/span&gt;
      &lt;label class&#x3D;&quot;portal-title&quot; data-code&#x3D;&quot;missing helper&quot;&gt;missing helper&lt;/label&gt;
      
    &lt;/li&gt;

    &lt;div class&#x3D;&quot;other-portals hidden&quot;&gt;
      &lt;ul class&#x3D;&quot;&quot;&gt;
      &lt;/ul&gt;
    &lt;/div&gt;
  &lt;/ul&gt;`

**Comment by nknapp** [comment]
Try calling `{{{inject "common/test"}}}` instead of `{{inject "common/test"}}` (triple brackets). This will prevent the output from being html-escaped.
Or you can let your helper create a `Handlebars.Safestring` which will also prevent escaping.
